apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: axonivy-engine
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: axonivy-engine
    spec:
      hostname: ivy
      containers:
      - image: localhost:5000/demo/portal 
        name: axonivy-engine
        ports:
        - containerPort: 8080
          protocol: TCP
