pipeline {
    agent any
    stages {
        stage('build') {
            steps{
                script {
                     sh "oc new-app https://github.com/jmindermann/axonIvy.git --name=ax13"
                }
            }
        }
    }
}
